=== Team302/2018PowerUp/config/compBot/robot.dtd
<!ELEMENT robot (navx?, pigeon?, pcm?, pdp?, lidar*, camera*, led?, chassis?, mechanism* )>

<!-- ====================================================
			enum NAVX_ORIENTATION 
			{
				FLAT_LOGO_TOWARD_BACK,
				FLAT_LOGO_TOWARD_FRONT,
				FLAT_LOGO_TOWARD_LEFT_SIDE,
				FLAT_LOGO_TOWARD_RIGHT_SIDE,
				MAX_NAVX_TYPES
			};
			
			enum NAVX_PORT 
			{
				SPI,
				I2C,
				SERIAL,
				MAX_NAVX_PORTS
			};

	==================================================== -->

<!ELEMENT navx EMPTY>
<!ATTLIST navx
		  orientation	( 0 | 1 | 2 | 3 ) "0"
		  porttype      ( 0 | 1 | 2 ) "0"
		  portid		CDATA #REQUIRED
		  updaterate	CDATA #IMPLIED
>

<!-- ====================================================
	 Pigeon IMU
	 ==================================================== -->
<!ELEMENT pigeon EMPTY>
<!ATTLIST pigeon 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
>

<!-- ====================================================
	 PCM (compressor) 
	 ==================================================== -->
<!ELEMENT pcm (analogInput?)>
<!ATTLIST pcm 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
>

<!-- ====================================================
	 PDP (power distribution panel) 
	 ==================================================== -->
<!ELEMENT pdp EMPTY>
<!ATTLIST pdp 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
>

<!-- ====================================================
	 LEDs
	 ==================================================== -->
<!ELEMENT led EMPTY>
<!ATTLIST led 
          canId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
>


<!-- ====================================================
     chassis type options 
     ====================================================
			enum CHASSIS_TYPE
			{
				UNKNOWN_CHASSIS = -1,
				TANK_CHASSIS,
				MECANUM_CHASSIS,
				MAX_CHASSIS_TYPES
			};


    Wheel Base is front-back distance between wheel centers 
    Track is the distance between wheels on an "axle"       
	==================================================== -->
<!ELEMENT chassis (motor*) >
<!ATTLIST chassis 
          type              ( 0 | 1 | 2  ) "0"
          wheelDiameter     CDATA #REQUIRED
          wheelBase         CDATA #REQUIRED
          track             CDATA #REQUIRED
>



<!-- ====================================================
        enum MECHANISM_TYPE
        {
            UNKNOWN_MECHANISM = -1,
            GRABBER,
            LIFT,
            CLIMBER,
            SIDE_HANGER,
            MAX_MECHANISM_TYPES
        };


	==================================================== -->
<!ELEMENT mechanism (motor*, analogInput*, digitalInput*, solenoid*, servo* )>
<!ATTLIST mechanism 
          type              ( 0 | 1 | 2 | 3 | 4 ) "0"
>


<!-- ====================================================
        enum LIDAR_USAGE
        {
            FORWARD_GRABBER,
            DOWNWARD_GRABBER,
            MAX_LIDAR_USAGES
        };

	==================================================== -->
<!ELEMENT lidar EMPTY>
<!ATTLIST lidar 
          usage              ( 0 | 1  ) "0"
          inputpin			 CDATA "0"
          triggerpin		 CDATA "0"
>

<!-- ====================================================
	 camera
	 
	    enum PIXEL_FORMAT
        {
                UNKNOWN_PIXEL_FORMAT = -1,
                KMJPEG,
                KYUYV,
                KRGB565,
                KBGR,
                KGRAY
        };
	==================================================== -->

<!ELEMENT camera EMPTY>
<!ATTLIST camera 
          type              ( 0 | 1 | 2 | 3 | 4 ) "0"
          width			 	CDATA "0"
          height		 	CDATA "0"
          fps			 	CDATA "0"
>


<!-- ====================================================
	 motor usage options 
	 ====================================================
		enum TALON_TYPE
		{
			UNKNOWN_TALON_TYPE = -1,
			MECANUM_FRONT_LEFT,
			MECANUM_FRONT_LEFT2,
			MECANUM_FRONT_RIGHT,
			MECANUM_FRONT_RIGHT2,
			MECANUM_BACK_LEFT,
			MECANUM_BACK_LEFT2,
			MECANUM_BACK_RIGHT,
			MECANUM_BACK_RIGHT2,
			TANK_LEFT_MASTER,
			TANK_LEFT_SLAVE1,
			TANK_LEFT_SLAVE2,
			TANK_RIGHT_MASTER,
			TANK_RIGHT_SLAVE1,
			TANK_RIGHT_SLAVE2,
			CLIMBER_MASTER,
			ELEVATOR_MASTER,
			ELEVATOR_SLAVE,
			SIDE_HANGER_MOTOR,
			ACTIVE_INTAKE_WHEELS,
			FOURBAR_LIFT_MOTOR,
			MAX_TALON_TYPES
		};

		
    ====================================================
    motor sensor types
    ====================================================
    	enum TALON_SENSOR_TYPE
		{
			NO_SENSOR = -1,
			QUAD_ENCODER,
			UNKNOWN_SENSOR,
			ANALOG_POT,
			ANALOG_ENCODER,
			ENCODER_RISING,
			ENCODER_FALLING,
			CTRE_MAG_ENCODER_RELATIVE,
			CTRE_MAG_ENCODER_ABSOLUTE,
			PULSE_WIDTH,
			MAX_SENSOR_TYPES
		};
	==================================================== -->
<!ELEMENT motor EMPTY>
<!ATTLIST motor 
          usage             		(  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
          					          10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 ) "0"
          canId             		(  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              		  10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              		  20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              		  30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              		  40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              		  50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              		  60 | 61 | 62 ) "0"
          type              		CDATA #FIXED "cantalon"
          inverted          		( true | false ) "false"
          sensorInverted    		( true | false ) "false"
          feedbackDevice    		( -1 | 0  |  2 |  3 |  4 |  5 |  6 |  7 |  8 ) "-1"
          countsPerRev      		CDATA "0"
          gearRatio         		CDATA "1"
          brakeMode         		( true | false ) "false"
          slaveTo 					CDATA "-1"
          peakCurrentDuration 		CDATA #IMPLIED
          continuousCurrentLimit 	CDATA #IMPLIED
          peakCurrentLimit			CDATA #IMPLIED
          currentLimiting   		( true | false ) "false"          
>


<!-- ====================================================
	 analogInput type options 
	 ====================================================
	 enum ANALOG_SENSOR_TYPE
	 {
	 	UNKNOWN_ANALOG_TYPE = -1,
	 	ANALOG_GENERAL,
	 	ANALOG_GYRO,
	 	POTENTIOMETER,
	 	PRESSURE_GAUGE,
	 	MAX_ANALOG_TYPES
	 };
	 ==================================================== -->
<!ELEMENT analogInput EMPTY>
<!ATTLIST analogInput 
          type              (  0 |  1 |  2 | 3 ) "0"
          analogId          (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 ) "0"
          voltageMin        CDATA "0.0"
          voltageMax        CDATA "5.0"
          outputMin         CDATA #REQUIRED
          outputMax         CDATA #REQUIRED
>

<!-- ====================================================
	 digitalInput 
	 ====================================================
		enum DIGITAL_INPUT_TYPE
		{
			UNKNOWN_DIGITAL_INPUT_TYPE = -1,
			CUBE_PRESENT,
			ELEVATOR_POSITION_0,
			ELEVATOR_POSITION_1,
			ELEVATOR_POSITION_2,
			ELEVATOR_POSITION_3,
			ELEVATOR_POSITION_4,
			ELEVATOR_POSITION_5,
			ELEVATOR_POSITION_6,
			MAX_DIGITAL_INPPUT_TYPES
		};

	 ==================================================== -->
<!ELEMENT digitalInput EMPTY>
<!ATTLIST digitalInput 
          usage             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 ) "0"
          digitalId         (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 ) "0"
          reversed          (true | false ) "false"
>

<!-- ====================================================
	 solenoid usage options 
     ==================================================== 
       enum DRAGON_SOLENOID_USAGE
        {
            CONTROL_4BAR,
            GRABBER_CLUTCH,
            GRABBER_POSITION,
            SIDEHANGER_LATCH,
            SIDEHANGER_LATCH2
        };
 	 ==================================================== -->
<!ELEMENT solenoid EMPTY>
<!ATTLIST solenoid 
          usage             (  0 |  1 | 2 | 3 | 4 ) "0"
          pcmId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
                              20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 
                              30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 
                              40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 
                              50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 
                              60 | 61 | 62 ) "0"
          channel			(  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 ) "0"
          reversed			( true | false ) "false"
>

<!-- ====================================================
	 servo usage options 
	 ====================================================
 		enum SERVO_USAGE
		{
			UNKNOWN_SERVO_USAGE = -1,
			SERVO_SIDEBAR_RELEASE_1,
			SERVO_SIDEBAR_RELEASE_2,
			MAX_SERVO_USAGES
		};

 	 ==================================================== -->
<!ELEMENT servo EMPTY>
<!ATTLIST servo 
          usage             (  0 |  1 | 2 ) "0"
          pwmId             (  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 
                              10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 ) "0"
          minAngle			CDATA "0.0"
          maxAngle          CDATA "180.0"
>

=== Team302/2018PowerUp/autonXML/robot.xml
<?xml version="1.0"?>
<!DOCTYPE robot SYSTEM "robot.dtd">
<robot>
   
<!-- ====================================================
	 NavX
	 ==================================================== -->    
	<navx orientation="0"
	      porttype="0"
	      portid="4" />    
    
<!-- ====================================================
	 Pigeon
	 ==================================================== -->    
    <pigeon canId="40" />
       
<!-- ====================================================
	 PCM
	 ==================================================== -->    
	<pcm canId="0">
		<!-- need to verify id -->
		<analogInput type="3"
					 analogId="0"
					 voltageMin="0.2"
					 voltageMax="4.8"
					 outputMin="0.0"
					 outputMax="200" />
    </pcm>
<!-- ====================================================
	 PDP
	 ==================================================== -->    
	<pdp canId="20" />
    
<!-- ====================================================
	 Lidars
	 ==================================================== -->    







	<!-- Downward Lidar  -->    

    <!-- lidar usage="1"
    	   inputpin="3"
    	   triggerpin="4" / -->






	<!-- Forward Lidar  -->    
    <lidar usage="0"
    	   inputpin="4"
    	   triggerpin="3" />
<!-- ====================================================
	 camera
	==================================================== -->
	<camera type="0"
			width="320"
			height="180"
			fps="15" />
<!-- ====================================================
	 LEDs
	 ==================================================== -->    
	<!-- led canId="30" / -->
       
<!-- ====================================================
	 Chassis
	 ====================================================  -->
    <chassis type="0"
    		 wheelDiameter="6.363"
             wheelBase="25.0"  
             track="18.0">
             
 		<!-- right back 11-->
        <motor usage="11"
        	   canId="13"
         	   feedbackDevice="0"
         	   countsPerRev="128"
		   brakeMode="true"
        	   gearRatio="11.0/18.0" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
 		<!-- left back 8-->
        <motor usage="8"
               canId="2"
               inverted="true"
		       sensorInverted="true"
        	   feedbackDevice="0"
          	   countsPerRev="128"
		   brakeMode="true"
        	   gearRatio="11.0/18.0" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
		<!-- right front 12-->
        <motor usage="12"
        	   canId="14"
        	   feedbackDevice="0"
         	   countsPerRev="128"
		   brakeMode="true"
        	   gearRatio="11.0/18.0"
        	   slaveTo="13"
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
		<!-- left front 9 -->
        <motor usage="9"
               canId="1"
               inverted="true"
         	   feedbackDevice="0"
          	   countsPerRev="128"
        	   gearRatio="11.0/18.0" 
        	   slaveTo="2"
        	   peakCurrentDuration="50"
        	   brakeMode="true"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
    </chassis>  
 
<!-- ====================================================
	 Mechanisms
	 ==================================================== -->    
   
    <!-- Grabber -->
    <mechanism type="4">
        <motor usage="18"
			   inverted="true"
        	   canId="3" />
    	<!-- clutch -->
	<!-- channel 1 previous -->
    	<solenoid usage="1"
    		      pcmId="0"
    		      channel="3"
    		      reversed="false" />
    </mechanism>    
     
    <!-- Lift -->
    <mechanism type="1">
        <motor usage="15"
        	   canId="4"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   brakeMode="true"
        	   gearRatio="70.0" 
        	   peakCurrentDuration="2"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="30" 
		   sensorInverted="true"
		   inverted="true"
        	   currentLimiting="true"  />
        <motor usage="16"
        	   canId="7"
        	   feedbackDevice="0"
         	   countsPerRev="256"
        	   gearRatio="70.0" 
        	   brakeMode="true" 
        	   slaveTo="4"
         	   peakCurrentDuration="2"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="35" 
		   inverted="true"
        	   currentLimiting="false"  />
	<digitalInput usage="4"
		digitalId="7"
		reversed="true" />
        <!-- 4 Bar -->
		<!-- channel 3 previous -->
    	<!--  <solenoid usage="0"
    		      pcmId="0"
    		      channel="1" 
    		      reversed="true" /> -->
        <motor usage="19"
        	   canId="6"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   sensorInverted="true"
		   inverted="true"
        	   gearRatio="1.0" 
        	   brakeMode="true" />
    </mechanism>    
     
    <!-- Climber -->
    <mechanism type="2">
    	<!-- winch -->
 	    <!-- TODO: verify gear ratio-->
        <motor usage="14"
        	   canId="11"
               inverted="true"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		       brakeMode="true"
        	   gearRatio="70.0" />
    </mechanism>    
     
    <!-- Side Hanger -->
    <mechanism type="3">
    	 <!-- side hanger motor -->
    	 <!-- TODO: verify gear ratio -->
         <motor usage="17"
         		canId="10"
		        brakeMode="true"
        	    gearRatio="70.0"  />
        <!-- side hanger latch -->
     	<solenoid usage="3"
    		      pcmId="0"
    		      channel="4"
    		      reversed="false" />
    </mechanism>
</robot>

=== Team302/2018PowerUp/config/robot.xml
<?xml version="1.0"?>
<!DOCTYPE robot SYSTEM "robot.dtd">
<robot>
   
<!-- ====================================================
	 NavX
	 ==================================================== -->    
	<navx orientation="0"
	      porttype="0"
	      portid="4" />    
    
<!-- ====================================================
	 Pigeon
	 ==================================================== -->    
    <pigeon canId="30" />
       
<!-- ====================================================
	 PCM
	 ==================================================== -->    
	<pcm canId="32">
		<analogInput type="3"
					 analogId="0"
					 voltageMin="0.5"
					 voltageMax="4.5"
					 outputMin="0.0"
					 outputMax="200" />
    </pcm>
<!-- ====================================================
	 PDP
	 ==================================================== -->    
	<pdp canId="31" />
    
<!-- ====================================================
	 Lidars
	 ==================================================== -->    
	<!-- Downward Lidar  -->    
    <lidar usage="1"
    	   inputpin="3"
    	   triggerpin="4" />
	<!-- Forward Lidar  -->    
    <lidar usage="0"
    	   inputpin="3"
    	   triggerpin="4" />
<!-- ====================================================
	 camera
	==================================================== -->
	<camera type="0"
			width="320"
			height="180"
			fps="15" />
       
<!-- ====================================================
	 Chassis
	 ====================================================  -->
    <chassis type="0"
    		 wheelDiameter="6.285"
             wheelBase="25.0"  
             track="18.0">
             
 		<!-- right back 11-->
        <motor usage="11"
        	   canId="14"
         	   feedbackDevice="0"
         	   countsPerRev="128"
		   	   brakeMode="true"
        	   gearRatio="11.0/18.0" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
         <motor usage="8"
               canId="1"
               inverted="true"
        	   feedbackDevice="0"
          	   countsPerRev="128"
		   	   brakeMode="true"
        	   gearRatio="11.0/18.0" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
		<!-- right front 12-->
        <motor usage="12"
        	   canId="15"
        	   feedbackDevice="0"
         	   countsPerRev="128"
		   	   brakeMode="true"
        	   gearRatio="11.0/18.0"
        	   slaveTo="14" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />
		<!-- left front 9 -->
        <motor usage="9"
               canId="0"
               inverted="true"
         	   feedbackDevice="0"
          	   countsPerRev="128"
		   	   brakeMode="true"
        	   gearRatio="11.0/18.0" 
        	   slaveTo="1" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="30"
        	   peakCurrentLimit="40" 
        	   currentLimiting="true"  />

               
    </chassis>  
 
<!-- ====================================================
	 Mechanisms
	 ==================================================== -->    
    
    <!-- Grabber -->
    <mechanism type="4">
        <motor usage="18"
	    inverted="true"
        	   canId="2" />
    	<!-- clutch -->
    	<solenoid usage="1"
    		      pcmId="32"
    		      channel="2"
    		      reversed="false" />
    </mechanism>    
     
    <!-- Lift -->
    <mechanism type="1">
        <motor usage="15"
        	   canId="4"
        	   feedbackDevice="0"
         	   countsPerRev="256"
			   brakeMode="true"
        	   gearRatio="70.0" 
        	   peakCurrentDuration="50"
        	   continuousCurrentLimit="25"
        	   peakCurrentLimit="30" 
        	   currentLimiting="true"  />

        <motor usage="16"
        	   canId="9"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		       inverted="true"
        	   gearRatio="10.0" 
        	   brakeMode="true" 
        	   slaveTo="4"
         	   peakCurrentDuration="50"
        	   continuousCurrentLimit="25"
        	   peakCurrentLimit="30" 
        	   currentLimiting="true"  />
        	   
		<!-- 4 Bar -->
        <motor usage="19"
        	   canId="6"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   	   sensorInverted="false"
		       inverted="true"
        	   gearRatio="1.0" 
        	   brakeMode="true" />
        	   
		<digitalInput usage="4"
					  digitalId="7"
		              reversed="true" />
    </mechanism>    
     
    <!-- Climber -->
    <mechanism type="2">
    	<!-- winch -->
        <motor usage="14"
        	   canId="11"
               inverted="false"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   	   brakeMode="true"
        	   gearRatio="70.0" />
    </mechanism>    
     
    <!-- Side Hanger -->
    <mechanism type="3">
    	 <!-- side hanger motor -->
         <motor usage="17"
         		canId="10"
		        brakeMode="true"
        	    gearRatio="70.0"  />
    </mechanism>
</robot>

=== Team302/2018PowerUp/config/compBot/robot.xml
<?xml version="1.0"?>
<!DOCTYPE robot SYSTEM "robot.dtd">
<robot>
   
<!-- ====================================================
	 NavX
	 ==================================================== -->    
	<navx orientation="0"
	      porttype="0"
	      portid="4" />    
    
<!-- ====================================================
	 Pigeon
	 ==================================================== -->    
    <pigeon canId="30" />
       
<!-- ====================================================
	 PCM
	 ==================================================== -->    
	<pcm canId="32">
		<!-- need to verify id -->
		<analogInput type="3"
					 analogId="0"
					 voltageMin="0.5"
					 voltageMax="4.5"
					 outputMin="0.0"
					 outputMax="200" />
    </pcm>
<!-- ====================================================
	 PDP
	 ==================================================== -->    
	<pdp canId="31" />
    
<!-- ====================================================
	 Chassis
	 ====================================================  -->
    <chassis type="0"
    		 wheelDiameter="6.285"
             wheelBase="25.0"  
             track="18.0">
             
 		<!-- right back 11-->
        <motor usage="11"
        	   canId="14"
         	   feedbackDevice="0"
         	   countsPerRev="128"
        	   gearRatio="11.0/18.0" />
		<!-- left back 8-->
        <motor usage="8"
               canId="1"
               inverted="true"
        	   feedbackDevice="0"
          	   countsPerRev="128"
        	   gearRatio="11.0/18.0" />            
		<!-- right front 12-->
        <motor usage="12"
        	   canId="15"
        	   feedbackDevice="0"
         	   countsPerRev="128"
        	   gearRatio="11.0/18.0"
        	   slaveTo="14" />
		<!-- left front 9 -->
        <motor usage="9"
               canId="0"
               inverted="true"
         	   feedbackDevice="0"
          	   countsPerRev="128"
        	   gearRatio="11.0/18.0" 
        	   slaveTo="1" />
    </chassis>  
 
<!-- ====================================================
	 Mechanisms
	 ==================================================== -->    
    
    <!-- Grabber -->
    <mechanism type="4">
        <motor usage="18"
			   inverted="true"
        	   canId="2" />
    	<!-- clutch -->
    	<solenoid usage="1"
    		      pcmId="32"
    		      channel="2"
    		      reversed="false" />
    </mechanism>    
     
    <!-- Lift -->
    <!-- TODO: verify gear ratio -->
    <mechanism type="1">
        <motor usage="15"
        	   canId="4"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   	   brakeMode="true"
        	   gearRatio="70.0" />
        <!-- todo need can id -->
        <motor usage="16"
        	   canId="9"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		       inverted="true"
        	   gearRatio="10.0" 
        	   brakeMode="true" 
        	   slaveTo="4" />
        <!-- 4 Bar -->
        <motor usage="19"
        	   canId="6"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		   	   sensorInverted="false"
		       inverted="true"
        	   gearRatio="1.0" 
        	   brakeMode="true" />
        	   
		<!-- digitalInput usage="4"
					  digitalId="7"
		              reversed="true" /  -->
    </mechanism>    
     
    <!-- Climber -->
    <mechanism type="2">
    	<!-- winch -->
        <motor usage="14"
        	   canId="11"
               inverted="false"
        	   feedbackDevice="0"
         	   countsPerRev="256"
		       brakeMode="true"
        	   gearRatio="70.0" />
    </mechanism>    
     
    <!-- Side Hanger -->
    <mechanism type="3">
    	 <!-- side hanger motor -->
         <motor usage="17"
         		canId="10"
		        brakeMode="true"
        	    gearRatio="70.0"  />
    </mechanism>

</robot>

=== Team302/2018PowerUp/config/thimg1/robot.xml
<?xml version="1.0"?>
<!DOCTYPE robot SYSTEM "robot.dtd">
<robot>
   
<!-- ====================================================
	 NavX
	 ==================================================== -->    
	<navx orientation="0"
	      porttype="0"
	      portid="4" />    
    
<!-- ====================================================
	 Pigeon
	 ==================================================== -->    
    <pigeon canId="40" />
       
<!-- ====================================================
	 PCM
	 ==================================================== -->    
	<pcm canId="13" />
       
<!-- ====================================================
	 PDP
	 ==================================================== -->    
	<pdp canId="10" />
    
<!-- ====================================================
	 LEDs
	 ==================================================== -->    
	<led canId="30" />
       
<!-- ====================================================
	 Chassis
	 ====================================================  -->
    <chassis type="0"
    		 wheelDiameter="6.363"
             wheelBase="25.0"  
             track="18.0">
             
 		<!-- right back 11-->
        <motor usage="11"
        	   canId="2"
         	   feedbackDevice="0"
         	   countsPerRev="128"
        	   gearRatio="11.0/18.0" />
		<!-- left back 8-->
        <motor usage="8"
               canId="3"
               inverted="true"
        	   feedbackDevice="0"
          	   countsPerRev="128"
        	   gearRatio="11.0/18.0" />            
		<!-- right front 12-->
        <motor usage="12"
        	   canId="0"
        	   feedbackDevice="0"
         	   countsPerRev="128"
        	   gearRatio="11.0/18.0"
        	   slaveTo="2" />
		<!-- left front 9 -->
        <motor usage="9"
               canId="1"
               inverted="true"
         	   feedbackDevice="0"
          	   countsPerRev="128"
        	   gearRatio="11.0/18.0" 
        	   slaveTo="3" />

               
    </chassis> 

</robot>
